framework:
  cache:
    default_redis_provider: app.cache.redis_provider
    prefix_seed: creative/symfony_learning
    app: cache.adapter.redis
    system: cache.adapter.redis

    pools:
      application.redis.cache:
        adapter: cache.adapter.redis
