security:
  # Password encoders
  encoders:
    App\Entity\SiteUser: # encoder for SiteUser entity
      algorithm: auto

  providers:
    app_user_provider:   # provider name (may be any string)
      entity:            # provider type (`entity` is an internal type)
        class: App\Entity\SiteUser
        property: email
    # used to reload user from session & other features (e.g. switch_user)
  firewalls:
    dev:                  # Firewall ID
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      pattern: /
      anonymous: true
      lazy: true
      provider: app_user_provider
      guard:
        authenticators:
          - App\Security\AppFormAuthenticator
      logout:
        path: app_logout
        target: model_index

  access_control:
    - { path: ^/api, roles: ROLE_ADMIN }
    - { path: ^/path/model/remove, roles: ROLE_ADMIN }
    - { path: ^/path/model/update, roles: ROLE_ADMIN }
    - { path: ^/path/model/new, roles: ROLE_ADMIN }
