version: '3.7'

services:
  database:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: webmaster
      POSTGRES_USER: webmaster
      POSTGRES_DB: symfony_learn
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  database:
    driver: 'local'
